version: "3.8"
services:

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  miflora:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: miflora-daemon
    restart: always
    environment:
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app
      - ./src/config.ini:/app/config.ini:ro 
    working_dir: /app
    command: python /app/miflora-mqtt-daemon.py
    depends_on:
      - mqtt